# Generated by Django 5.2.7 on 2025-10-03 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros_custos', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('sinal', models.CharField(choices=[('+', 'Entrada'), ('-', 'Saida')], max_length=1)),
                ('historico', models.TextField()),
                ('centro_custos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='centros_custos.centrocusto')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
                'db_table': 'movimento',
                'ordering': ['-data'],
            },
        ),
    ]
