# Generated by Django 5.2.7 on 2025-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='historico',
            field=models.TextField(verbose_name='HistÃ³rico'),
        ),
    ]
